name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Vercel
      env:
        VERCEL_TOKEN: ${{ C24nee9Yy98i3Cmi1eR9dYbU }}
      run: |
        npm install -g vercel
        vercel --prod --confirm --token $VERCEL_TOKEN
